chrome-duplicate-tab.applescript: do not emulate key strokes
jordansaints/scripts pull request #1
Opened 2017-04-24 12:30 UTC by vitorgalvao

Faking key strokes is error prone. Chrome has proper AppleScript support for this.

2017-06-28 12:19 UTC, jordansaints requested changes
Freaking cool, did not know that. This script was written for like OS X 10.7 so I haven't even looked at it in months cause it was still working :P

Mind re-adding the attribution line?

2017-06-28 12:20 UTC, jordansaints commented
Can merge and make the update myself too :) haven't checked this repo in a long time, apologies for the late response!

2017-06-28 12:42 UTC, vitorgalvao commented
> Mind re-adding the attribution line?

It wouldn’t make sense. I changed everything substantial about the script; it can no longer be truthfully attributed to you.

Also, it’s not like the code is doing something novel. It’s just calling an API that is doing all the work. Adding an attribution line to what is essentially a snippet is nonsensical — there’s no claim of authenticity to be made. If anyone, it would be the Chromium developer that added this capability that could be credited.

2017-06-28 13:39 UTC, jordansaints commented
> there’s no claim of authenticity to be made

No claims of authenticity or uniqueness of the code are being made. The attribution is there because I was the one that whipped the snippet up and threw it up in this repo initially, so I want to give people someone to yell at if my code broke their stuff :P

> I changed everything substantial about the script

Feel free to include yourself in there if you'd like!

2017-06-28 16:23 UTC, vitorgalvao commented
> The attribution is there because I was the one that whipped the snippet up

But it’s not your code in this change. Nothing relevant from your original code remains, so attributing it to you would be false.

It’s just a snippet that calls an established API. If something breaks it’s not in the code but in Chrome.

Finally, there’s nothing particularly original abou the snippet. It’s a common call. There’s no point in having it attributed to *anyone*.

Anyone could get to this by reading the AppleScript dictionary or searching Stack Overflow. I found this my mistake and made the change because it will benefit you. It’s extremely unlikely anyone else will get great value from this fix in your repo.

2017-06-29 03:50 UTC, jordansaints commented
So critical, are we :) this was only ever a repo for silly crap I automated in college. If no one else gets great value out of it, fine by me.

Will have a chance to test and merge after this week of work.

2017-06-29 08:59 UTC, vitorgalvao commented
> If no one else gets great value out of it, fine by me.

Precisely. If I didn’t think that, I wouldn’t have submitted the improvement. It’s not uncommon for me to find deserted repos where I find small things that could be improved, and improve them. If the one repo owner gets value from it, that’s enough for me.

Most people just merge it with a thank you and we all get on with our lives.

2017-06-29 17:48 UTC, jordansaints commented
These scripts get auto updated across all my machines, so testing is required first. Thank you for the upgrade.

2018-04-28 14:57 UTC, closed without merging